# ----
# Site

title: MDEOptimiser
url: "https://mde-optimiser.github.io"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Tool documentation website for MDEOptimiser.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: MDEOptimiser
  links:
    - https://github.com/mde-optimiser

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll/scholar

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major

#------------
# Jekyll scholar
scholar:
  style: apa
